const projects = [
  {
    coreTechnology: 'react',
    level: 'Junior',
    name: 'E-Commerce de produtos de casa',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'nodejs', 'vuejs', 'typescript', 'mongodb', 'dotnetcore', 'php'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'angularjs',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'javascript',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'nodejs',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'vuejs',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },

  {
    coreTechnology: 'typescript',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'mongodb',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'dotnetcore',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'php',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'mysql',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: [
      'javascript',
      'react',
      'angularjs',
      'javascript',
      'react',
      'angularjs',
      'javascript',
      'react',
      'angularjs',
      'javascript',
      'react',
      'angularjs',
      'javascript',
      'react',
      'angularjs',
    ],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },

  {
    coreTechnology: 'csharp',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'python',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'nestjs',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'figma',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'java',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'postgresql',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
  {
    coreTechnology: 'flutter',
    level: 'Junior',
    name: 'Streaming de video',
    owner: 'William',
    participants: ['1', '2', '2'],
    technologies: ['javascript', 'react', 'angularjs'],
    likes: 10,
    description:
      'Lorem ipsum dolor sit amet, consectetur lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem',
    views: 12,
  },
]

export default projects
